import time
import sys
import colorama
from colorama import Fore,Style
import time

def slowprint(s):
		for c in s + '\n' :
			sys.stdout.write(c)
			sys.stdout.flush()
			time.sleep(10 / 250)

print(Fore.RED + "##################################################################")
print("##################################################################")
print("##                                                              ##")
print("##                                                              ##")
print("##                                                              ##")
print("##                                                              ##")
print("##################################################################")
print("##################################################################")
slowprint("             WELCOMOE TO PROVERBS REALMS")
slowprint(Fore.CYAN + "[+] 1 AFRICAN PROVERBS")
slowprint("[+] 2 AUROPE PROVERBS")
slowprint("[+] 3 ASIAN PROVERBS")
slowprint("[+] 4 AMERICAN PROVERBS")
user = int(input("CHOOSE AMONG THEM: \n"))
if user == 1:
	print("Loading................................")
	time.sleep(2)
	print(Fore.LIGHTGREEN_EX + "||| AFRICAN PROVERV ARE THE BEST |||")
	print("##################################################################")
	print("##################################################################")
	slowprint("* A chattering bird builds no nest: A proverb that encourages people to stop talking about what they want to do and actually do it.")
	print("                                                                                                         Nigerian:\n")
	slowprint("* A child that does not cry will die in the carrier.")
	print("                                                         Ghana:\n")
	slowprint("* A person is a person because of other people.")
	print("                                     Ivory coast:\n")
	slowprint("* The best way to eat an elephant in your path is to cut him up into little pieces.")
	print("                                                             South Africa:\n")
	slowprint("* Knowledge is a garden. If it isn't cultivated, you can't harvest it")
	print("                                             Cameroon:\n")
	slowprint("* One falsehood spoils a thousand truths")
	print("                   Morocco:\n")
	slowprint("* We do not inherit the earth from our ancestors. We borrow it from our children. ")
	print("                                                             Mali:")
if user == 2:
	print("Loading................................")
	time.sleep(2)
	print(Fore.GREEN + "||| auropes PROVERV ARE THE BEST |||")
	print("##################################################################")
	print("##################################################################")
	slowprint("* Shared joy is double joy. Shared sorrow is half sorrow.")
	print("                                   swedish:")
	slowprint("* Who has wine for dinner, he has water for breakfast.")
	print("                           serbian:")
	slowprint("* it is too late to learn to swim when the water is up to your lips..")
	print("                           denish:")
	slowprint("* The eyes believe themselves; the ears believe other people.")
	print("                           german:")
	slowprint("Listen to the sound of the river and you will get a trout.")
	print("                                 English:")
	slowprint("Woe to the house where the weasel is in the eggs and the dog sleeps soundly.")
	print("                                              Polish")
if user == 3:
	print("Loading................................")
	time.sleep(2)
	print(Fore.YELLOW + "||| Asian PROVERV ARE THE BEST |||")
	print("##################################################################")
	print("##################################################################")
	slowprint("* Building a house by the roadside takes more than three years")
	print("                                                   China:")
	slowprint("* There is no victory in winning a hundred battles. There is victory in subduing your enemy without fighting at all.")
	print("                                                                                Singapore:")
	slowprint("* He is victorious who knows when and when not to fight.")
	print("                                   Arabs:")
	slowprint("* True gold fears not the test of fire. ")
	print("                      India:")
if user == 4:
	print("Loading................................")
	time.sleep(2)
	print(Fore.MAGENTA + "||| American PROVERV ARE THE BEST |||")
	print("##################################################################")
	print("##################################################################")
	slowprint("* Actions speak louder than words: A person's true character is seen by what they do, not what they say.")
	print("                       america:")
	slowprint("* Absence makes the heart grow fonder: This proverb describes the feeling of greater affection between friends and lovers who are kept apart.")
	print("                                                                                             america:")
	slowprint("* The early bird catches the worm: This proverb means that the person who arrives first in a place is most likely to get what they want. ")
	print("                                                                                            America:")

print("***********************************************************************************************")
print("************************************* THANKS FOR YOUR TIME  ***********************************")
print("***********************************************************************************************")
